build:
  dir: builds/456
  description: LGBM test 1

data:
  path: data/raw
  train: train.csv
  test: test.csv
  id_col: id
  target_col: FloodProbability

feature_engineering:
  path: src/feature_engineering.py

preprocess:
  path: src/preprocess.py

feature_selection:
  path: src/feature_selection.py

model:
  type: lgbm
  parameters:
    random_state: 123
    verbosity: -1
    boosting_type: gbdt
    n_estimators: 2000
    learning_rate: 0.012
    num_leaves: 250
    subsample_for_bin: 165700
    min_child_samples: 114
    reg_alpha: 2.075e-06
    reg_lambda: 3.839e-07
    colsample_bytree: 0.9634
    subsample: 0.9592
    max_depth: 10

metrics:
  name: r2

cross_validation:
  random_state: 123
  n_folds: 5
