build:
  dir: builds/2
  description: LGBM features 1

data:
  path: data/raw
  train: train.csv
  test: test.csv
  id_col: id
  target_col: FloodProbability

feature_engineering:
  path: src/feature_engineering/feature_engineering1.py

preprocess:
  path: src/preprocess.py

feature_selection:
  path: src/feature_selection.py

model:
  type: lgbm
  parameters:
    boosting_type: gbdt
    colsample_bytree: 0.964
    learning_rate: 0.012
    max_depth: 10
    min_child_samples: 110
    n_estimators: 500
    num_leaves: 250
    reg_alpha: 2.075e-06
    reg_lambda: 3.839e-07
    subsample: 0.9592
    subsample_for_bin: 165700
    random_state: 123
    verbosity: -1

train:
  parameters:
    # early_stopping_rounds: 50
    # verbose: 100

metrics:
  name: r2

cross_validation:
  random_state: 123
  n_folds: 5

optuna:
  storage: sqlite
  study_name: hyperparameter optimization
  direction: maximize
  n_trials: 2

  sampler:
    type: TPESampler
    parameters:
      seed: 123

  pruner:
    type: HyperbandPruner
    parameters:
      max_resource: 5
