build:
  dir: builds/789
  description: XGB Optuna 1

data:
  path: data/raw
  train: train.csv
  test: test.csv
  id_col: id
  target_col: FloodProbability

feature_engineering:
  path: src/feature_engineering.py

preprocess:
  path: src/preprocess.py

feature_selection:
  path: src/feature_selection.py

model:
  type: xgb
  parameters:
    learning_rate: 0.1
    max_depth: 6
    n_estimators: 100
    n_jobs: 20
    random_state: 123
    verbose: -1

metrics:
  name: r2

cross_validation:
  random_state: 123
  n_folds: 5

optuna:
  storage: sqlite
  study_name: hyperparameter optimization
  direction: maximize
  n_trials: 100

  sampler:
    type: TPESampler
    parameters:
      seed: 123

  pruner:
    type: HyperbandPruner
    parameters:
      max_resource: 5
